### ISSUE TITLE
Ownership of th-rosenheim

### ISSUE THREAD

**Issue by throbach** [th-rosenheim/wow#1]
Dear owner of this organisation,

Since this organisation looks like an abaddonned one and more like a test, I would like to ask you kindly if the Technische Hochschule Rosenheim (TH Rosenheim, Rosenheim Technical University of Applied Sciences) could use the name of this GitHub organisation (th-rosenheim) for its purposes? If you want to contact me, feel free to invite me to this organisation or contact the it-helpdesk of TH Rosenheim (Sorry, I don't want to publish my email address in a public repository to avoid spam bots). 

Thanks in advance and best regards

Christian Bauer
Member of the it-department at TH Rosenheim

**Comment by 6543** [comment]
@throbach sorry to reach out just now ... (gh notification sucks!!!)

sure it was intended to be moved into the official hands all along ... but back when it was created there was no one who did take that effen serious.

this repo was to get issues like this :point_up: , so it kinda worked out in the end :)

PS: we can chat via internal mail, I'll open a channel

**Comment by 6543** [comment]
@throbach confirmed your identity and invited u

**Comment by 6543** [comment]
@throbach you should now be org admin :)

feel free to administer ;)
